package com.jlh.keytar.common;

public class IPCMessage {
    private String type;
    private String name;
    private String data;

    public IPCMessage(){}

    public IPCMessage(String type, String name) {
        this.type = type;
        this.name = name;
        data = null;
    }

    public IPCMessage(String type, String name, String data) {
        this.type = type;
        this.name = name;
        this.data = data;
    }


    public String getType() {
        return this.type;
    }


    public String getName() {
        return this.name;
    }


    public String getData() {
        return this.data;
    }

    /*Generated by VSCode */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        IPCMessage other = (IPCMessage) obj;
        if (type == null) {
            if (other.type != null)
                return false;
        } else if (!type.equals(other.type))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        } else if (!name.equals(other.name))
            return false;
        if (data == null) {
            if (other.data != null)
                return false;
        } else if (!data.equals(other.data))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "IPCMessage [type=" + type + ", name=" + name + ", data=" + data + "]";
    }



}